/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Viewer;

import java.awt.Color;
import static java.awt.Component.CENTER_ALIGNMENT;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;

public class Startframe extends javax.swing.JFrame implements ActionListener{

    Timer t;
    int i = 0;
    Graphics g;
    ImageIcon start = new ImageIcon("start.png");
    ImageIcon exit = new ImageIcon("exit.png");
    Mazeframe m = new Mazeframe();
    /**
     * Creates new form Startframe
     */
    public Startframe() {
        initComponents();
         m.setVisible(false);
    g = getGraphics();
        this.setSize(540, 453);
        Icons.setSize(600, 600);
        //jPanel1.setBackground(Color.WHITE);
        t = new Timer(100,this);
        
        //jLabel1.setVisible(false);
        //jLabel2.setVisible(false);
        jLabel1.setVisible(true);
                jLabel2.setVisible(true);
        t.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Icons = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Start Game");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 3, true));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 120, 140, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Exit");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 3, true));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(180, 210, 140, 60);

        Icons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Viewer/maze.jpg"))); // NOI18N
        Icons.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IconsMousePressed(evt);
            }
        });
        jPanel1.add(Icons);
        Icons.setBounds(0, 0, 470, 330);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IconsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconsMousePressed
        
    }//GEN-LAST:event_IconsMousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_jLabel3MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Startframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Startframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Startframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Startframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Startframe().setVisible(true);
            }
        });
    }

    
    @Override
    public void actionPerformed(ActionEvent ae) {
        g.setFont(new Font("Comic Sans MS", Font.BOLD , 38));
        g.setColor(Color.YELLOW);
       // g.drawRect(100, 100, 100, 100);
        switch(i)
        {
            case 0 : 
            {
                g.drawString("M", 80, 80);
                break;
            }
            case 1 : 
            {
                g.drawString("A", 120, 80);
                break;
            }
            case 2 : 
            {
                g.drawString("Z", 160, 80);
                break;
            }
            case 3 : 
            {
                g.drawString("E", 200, 80);
                break;
            }
            case 4 : 
            {
                g.drawString("R", 250, 80);
                break;
            }
            case 5 : 
            {
                g.drawString("U", 290, 80);
                break;
            }
            case 6 : 
            {
                g.drawString("N", 330, 80);
                break;
            }
            case 7 : 
            {
                g.drawString("N", 370, 80);
                break;
            }
            case 8 : 
            {
                g.drawString("E", 410, 80);
                break;
            }
            case 9 : 
            {
                g.drawString("R", 450, 80);
                jLabel1.setAlignmentX(CENTER_ALIGNMENT);
                jLabel1.setAlignmentY(CENTER_ALIGNMENT);
                jLabel2.setAlignmentX(CENTER_ALIGNMENT);
                jLabel2.setAlignmentY(CENTER_ALIGNMENT);
                
                break;
            }
            
        }
        i++;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icons;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
